// interface/app/$libraryId/Explorer/File/RenameTextBox.tsx
import clsx from 'clsx';
import { HTMLAttributes, useEffect, useRef, useState } from 'react';
import { useKey } from 'rooks';
import { FilePath, useLibraryMutation } from '@sd/client';
import useClickOutside from '~/hooks/useClickOutside';
import { useOperatingSystem } from '~/hooks/useOperatingSystem';
import { useExplorerViewContext } from '../ViewContext';

interface Props extends HTMLAttributes<HTMLDivElement> {
	filePathData: FilePath;
	activeClassName?: string;
	disabled?: boolean;
}

export default ({ filePathData, className, activeClassName, disabled, ...props }: Props) => {
	const explorerView = useExplorerViewContext();
	const os = useOperatingSystem();

	const ref = useRef<HTMLDivElement>(null);

	const [allowRename, setAllowRename] = useState(false);
	const [renamable, setRenamable] = useState(false);

	const renameFile = useLibraryMutation(['files.renameFile'], {
		onError: () => reset()
	});

	const fileName = `${filePathData?.name}${
		filePathData?.extension && `.${filePathData.extension}`
	}`;

	// Reset to original file name
	function reset() {
		if (ref.current) {
			ref.current.innerText = fileName;
		}
	}

	// Handle renaming
	function rename() {
		if (ref.current) {
			const innerText = ref.current.innerText.trim();
			if (!innerText) return reset();

			const newName = innerText;
			if (filePathData) {
				const oldName =
					filePathData.is_dir || !filePathData.extension
						? filePathData.name
						: filePathData.name + '.' + filePathData.extension;

				if (newName !== oldName) {
					renameFile.mutate({
						location_id: filePathData.location_id,
						file_name: oldName,
						new_file_name: newName
					});
				}
			}
		}
	}

	// Highlight file name up to extension or
	// fully if it's a directory or has no extension
	function highlightFileName() {
		if (ref.current) {
			const range = document.createRange();
			const node = ref.current.firstChild;
			if (!node) return;

			range.setStart(node, 0);
			range.setEnd(node, filePathData?.name.length || 0);

			const sel = window.getSelection();
			sel?.removeAllRanges();
			sel?.addRange(range);
		}
	}

	// Blur field
	function blur() {
		if (ref.current) {
			ref.current.blur();
			setAllowRename(false);
		}
	}

	// Handle keydown events
	function handleKeyDown(e: React.KeyboardEvent<HTMLDivElement>) {
		switch (e.key) {
			case 'Tab':
				e.preventDefault();
				blur();
				break;
			case 'Escape':
				reset();
				blur();
				break;
			case 'z':
				if (os === 'macOS' ? e.metaKey : e.ctrlKey) {
					reset();
					highlightFileName();
				}
				break;
		}
	}

	// Focus and highlight when renaming is allowed
	useEffect(() => {
		if (allowRename) {
			explorerView.setIsRenaming(true);
			setTimeout(() => {
				if (ref.current) {
					ref.current.focus();
					highlightFileName();
				}
			});
		}
	}, [allowRename]);

	// Handle renaming when triggered from outside
	useEffect(() => {
		if (!disabled) {
			if (explorerView.isRenaming && !allowRename) setAllowRename(true);
			else if (!explorerView.isRenaming && allowRename) setAllowRename(false);
		}
	}, [explorerView.isRenaming]);

	useEffect(() => {
		function handleClickOutside(event: MouseEvent) {
			if (ref.current && !ref.current.contains(event.target as Node)) {
				blur();
			}
		}

		document.addEventListener('mousedown', handleClickOutside, true);
		return () => {
			document.removeEventListener('mousedown', handleClickOutside, true);
		};
	}, [ref]);

	// Rename or blur on Enter key
	useKey('Enter', (e) => {
		if (allowRename) {
			e.preventDefault();
			blur();
		} else if (!disabled) setAllowRename(true);
	});

	return (
		<div
			ref={ref}
			role="textbox"
			contentEditable={allowRename}
			suppressContentEditableWarning
			className={clsx(
				'cursor-default overflow-y-auto truncate rounded-md px-1.5 py-px text-xs text-ink',
				allowRename && [
					'whitespace-normal bg-app outline-none ring-2 ring-accent-deep',
					activeClassName
				],
				className
			)}
			onDoubleClick={(e) => e.stopPropagation()}
			onMouseDown={(e) => e.button === 0 && setRenamable(!disabled)}
			onMouseUp={(e) => {
				if (e.button === 0) {
					if (renamable) {
						setAllowRename(true);
					}
					setRenamable(false);
				}
			}}
			onBlur={() => {
				rename();
				setAllowRename(false);
				explorerView.setIsRenaming(false);
			}}
			onKeyDown={handleKeyDown}
			{...props}
		>
			{fileName}
		</div>
	);
};

// interface/app/$libraryId/Explorer/FilePath/RenameTextBox.solid.tsx
/** @jsxImportSource solid-js */

import clsx from 'clsx';
import { createSignal, onMount } from 'solid-js';
import { EventPairRegister, OperatingSystem } from '@sd/client';

import { TruncateMarkupSolid } from './TruncateMarkup.solid';

export interface RenameTextBoxProps extends React.HTMLAttributes<HTMLDivElement> {
	name: string;
	onRename: (newName: string) => void;
	disabled?: boolean;
	lines: number;
	// Temporary solution for TruncatedText in list view
	idleClassName?: string;

	// TODO: Remove all this in future.
	_temporary_os: OperatingSystem;
	_temporary_renameObject: EventPairRegister<KeyboardEvent>;
}

export function RenameTextBox2(props: RenameTextBoxProps) {
	const os = props._temporary_os; // TODO: Get using a hook

	let ref: HTMLDivElement | undefined;

	let renamable = false;
	let timeout: NodeJS.Timeout | null = null;

	const [allowRename, setAllowRename] = createSignal(false);
	const [isTruncated, setIsTruncated] = createSignal(false);

	// Highlight file name up to extension or
	// fully if it's a directory, hidden file or has no extension
	const highlightText = () => {
		if (!ref || !props.name) return;

		const node = ref.firstChild;
		if (!node) return;

		const endRange = props.name.lastIndexOf('.');

		const range = document.createRange();

		range.setStart(node, 0);
		range.setEnd(node, endRange > 1 ? endRange : props.name.length);

		const sel = window.getSelection();
		if (!sel) return;

		sel.removeAllRanges();
		sel.addRange(range);
	};

	const reset = () => ref && (ref.innerText = props.name ?? '');

	const handleRename = async () => {
		let newName = ref?.innerText;

		if (newName?.endsWith('\n')) newName = newName.slice(0, -1);

		if (!newName || newName === props.name) {
			reset();
			return;
		}

		props.onRename(newName);
	};

	const handleKeyDown = (e: unknown) => {
		switch (e.key) {
			case 'Tab': {
				e.preventDefault();
				ref?.blur();
				break;
			}
			case 'Escape': {
				e.stopPropagation();
				reset();
				ref?.blur();
				break;
			}
			case 'z': {
				if (os === 'macOS' ? e.metaKey : e.ctrlKey) {
					reset();
					highlightText();
				}
			}
		}
	};

	const resetState = () => {
		setAllowRename(false);
		renamable = false;
		if (timeout) {
			clearTimeout(timeout);
			timeout = null;
		}
	};

	props._temporary_renameObject((e) => {
		console.log('ON RENAME');

		e.preventDefault();
		if (allowRename()) ref?.blur();
		else if (!props.disabled) setAllowRename(true);
	});

	// TODO
	// useEffect(() => {
	// 	const element = ref.current;
	// 	if (!element || !allowRename) return;

	// 	const scroll = (e: WheelEvent) => {
	// 		e.preventDefault();
	// 		element.scrollTop += e.deltaY;
	// 	};

	// 	highlightText();

	// 	element.addEventListener('wheel', scroll);
	// 	return () => element.removeEventListener('wheel', scroll);
	// }, [allowRename, highlightText]);

	// TODO
	// useEffect(() => {
	// 	if (!disabled) {
	// 		if (isRenaming && !allowRename) setAllowRename(true);
	// 		else explorerStore.isRenaming = allowRename;
	// 	} else resetState();
	// }, [isRenaming, disabled, allowRename]);

	// TODO
	// useEffect(() => {
	// 	const onMouseDown = (event: MouseEvent) => {
	// 		if (!ref.current?.contains(event.target as Node)) blur();
	// 	};

	// 	document.addEventListener('mousedown', onMouseDown, true);
	// 	return () => document.removeEventListener('mousedown', onMouseDown, true);
	// }, [blur]);

	// onMount(() => {
	// 	ref?.addEventListener('mouseover', () => {
	// 		console.log('MOUSE OVER');
	// 	});

	// 	ref?.addEventListener('keydown', () => {
	// 		console.log('KEY DOWN');
	// 	});
	// });

	return (
		<div
			ref={ref}
			role="textbox"
			autoCorrect="off"
			contenteditable={allowRename()}
			class={clsx(
				'cursor-default overflow-hidden rounded-md px-1.5 py-px text-xs text-ink outline-none',
				allowRename() && 'whitespace-normal bg-app !text-ink ring-2 ring-accent-deep',
				!allowRename() && props.idleClassName,
				props.className
			)}
			onDblClick={(e) => {
				if (allowRename()) e.stopPropagation();
				renamable = false;
			}}
			onMouseDown={(e) => {
				e.button === 0 && (renamable = !props.disabled);
			}}
			onMouseUp={(e) => {
				if (e.button === 0 || renamable || !allowRename) {
					timeout = setTimeout(() => renamable && setAllowRename(true), 350);
				}
			}}
			onBlur={(e) => {
				handleRename();
				resetState();
				explorerStore.isRenaming = false;
			}}
			onKeyDown={handleKeyDown}
			{...props}
		>
			{allowRename() ? (
				props.name
			) : (
				<TruncatedTextWrapperSolid
					text={props.name}
					lines={props.lines}
					onTruncate={setIsTruncated}
				/>
			)}
		</div>
	);
}

interface TruncatedTextProps {
	text: string;
	lines: number;
	onTruncate: (wasTruncated: boolean) => void;
}

export function TruncatedTextWrapperSolid(props: TruncatedTextProps) {
	const ellipsis = () => {
		const extension = props.text.lastIndexOf('.');
		if (extension !== -1) return `...${props.text.slice(-(props.text.length - extension + 2))}`;
		return `...${props.text.slice(-8)}`;
	};

	return (
		<TruncateMarkupSolid
			postfix={ellipsis()}
			content={props.text}
			lines={props.lines}
			onTruncate={props.onTruncate}
		/>
	);
}
